# Generated by Django 4.1.1 on 2022-10-08 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.IntegerField()),
            ],
            options={
                'db_table': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Buildingaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_timestamp', models.DateTimeField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.buildings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.users')),
            ],
            options={
                'db_table': 'buildingaccess',
                'unique_together': {('user', 'building', 'access_timestamp')},
            },
        ),
    ]
